=== ugy420/colDump/CTE308/lab03/item.xsd
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
elementFormDefault="qualified">
  <xs:element name="Item_catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Food_Item" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Name"/>
              <xs:element type="xs:string" name="Price"/>
              <xs:element type="xs:string" name="Calories"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ugy420/colDump/CTE308/lab03/item.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="item.xslt"?>
<Item_catalog xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="item.xsd">
   <Food_Item>
      <Name>Watermelon</Name>
      <Price>Nu.400</Price>
      <Calories>1400 cal</Calories>
   </Food_Item>
   <Food_Item>
      <Name>Apple</Name>
      <Price>Nu.100</Price>
      <Calories>50 cal</Calories>
   </Food_Item>
   <Food_Item>
      <Name>Banana</Name>
      <Price>Nu.250</Price>
      <Calories>105 cal</Calories>
   </Food_Item>
</Item_catalog>
