=== ugy420/colDump/CTE308/lab02/movie_catalog.dtd
<!DOCTYPE movie
[
    <!ELEMENT movie_catalog (movie+)>
    <!ELEMENT movie (title,director,release_year,genre,price,imdb_rating)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT release_year (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT imdb_rating (#PCDATA)>
]>

=== ugy420/colDump/CTE308/lab02/movie_catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movie_catalog SYSTEM "movie_catalog.dtd">
<movie_catalog>
    <movie>
        <title>Oppenheimer</title>
        <director>Christopher Nolan</director>
        <release_year>2023</release_year>
        <genre>History</genre>
        <price>Nu.250</price>
        <imdb_rating>8.6</imdb_rating>
    </movie>
    <movie>
        <title>El Camino</title>
        <director>Vince Gilligan</director>
        <release_year>2019</release_year>
        <genre>Crime-Drama</genre>
        <price>Nu.300</price>
        <imdb_rating>7.3</imdb_rating>
    </movie>
    <movie>
        <title>Lunana: A Yak in the Classroom</title>
        <director>Pawo Choyning Dorji</director>
        <release_year>2019</release_year>
        <genre>Adventure/Comedy</genre>
        <price>Nu.400</price>
        <imdb_rating>7.4</imdb_rating>
    </movie>
</movie_catalog>
